### PR TITLE
fix 3FHL validation for gammapy v0.18.2

### PR DESCRIPTION
**Pull request by QRemy**
This PR fix 3FHL validation for gammapy v0.18.2.
- The main problem was that the changes in datasets.write() was not taken into account so the new models file was not saved, and the datasets.read() method was using old files.
- The second problem was that the old file rely on a PSFkernel that is no longer read using lazy loading  on datasets.read()  by default (have to explicitly use lazy=False).
- After fixing the IO results are back to normal, but the computation time is increased by a factor 2 to 3 due to the use of a PSFmap instead of a PSFkernel. In order to improve performance I restored the previous approach and used a PSFkernel.
- Last problem, the size of the psf_kernel_map was based on the 99 containment radius of the PSF a 10 GeV but in the new version psf.containment_radius() seems to no longer extrapolate the values beyond the edges but clip to zero . Then in order to get the correct shape I computed containment radius for all the energies of the geom and picked the max. 

Further changes are necessary to update to the latest dev version due to new changes in PSF methods, this will be done in a separate PR.

### CODE REVIEW

**Comment by Bultako** [comment]
Hi @QRemy 
validations workflows in this repo use the dev version of Gammapy. I would propose to continue in this PR with the modifs needed to have the 3FHL validation working with last devels on PSF methods.

**Comment by QRemy** [comment]
Hi,
ok I will continue from there, I just wanted to be sure that everything was fine with v0.18.2 and that the odd results was coming from the validation code itself.

**Comment by QRemy** [comment]
After the update to the current gammapy master (after merging of PR#3212), there is several problems:
- datasets.write() is broken because the psf format is not set to the correct one in self.psf.to_hdulist(). I guess that the format should defined an an attribute of the psf to be re-used later.
- the fit is failing in one of the test region (ROI_num277), looking at the predicted counts maps it seems that the psf have not been applied. This is likely related to the use of PSFmap but I have to look deeper into this,  @adonath any idea ? 
- missing upper limit in several ROIs, this is related to the hard-coded bounds in the FluxPointsEstimator, in particular the negative lower bound which causes the upper limit computation to fail. I will open a PR to fix this.

**Comment by adonath** [comment]
Thanks a lot @QRemy! 
- I'm aware of the issue with `MapDataset.write()` and I can put a fix for it. I'll add a `PSFMap.inter_to_geom()` method, which allows to easily convert the `PSFMap` into `WcsGeom` again, I already have a working draft.
- Maybe it's related to the selection of the nearest valid IRF as well, I can help to debug if needed.

**Pull request merged**
