### PR TITLE
Add 3FHL validation

### PR DESCRIPTION
**Pull request by QRemy**
add 3FHL validation prototype notebook

### CODE REVIEW

**Comment by cdeil** [comment]
Remove `.DS_Store` from here, and add it to `.gitignore`, then merge please.

**Comment by cdeil** [comment]
Can you change the `/Users/qremy/Work/Data/` to use relative paths or env vars please?
Anyone that has the data should be able to run them without having to edit your notebooks or sripts.

**Comment by cdeil** [comment]
And well, it's Spaghetti code: https://github.com/gammapy/gammapy-benchmarks/blob/a54c979a18e9b332df78271215dfc9f1843300b1/validation/fermi-3fhl/checks.ipynb

So the next task is to refactor to have functions and / or classes to make it maintainable.
I strongly suggest to change from notebook to Python script with a CLI (`make.py`), makes code review and running easier.

I would work on clean code first, and then continue with results and benchmarks, because it'll let us move faster overall. But of course up to you ... if you want to just get results for Monday, and then improve code and do code review next week, fine.

**Comment by cdeil** [comment]
````
try:
    <100 lines>
except:
     pass
```
🙈

**Comment by QRemy** [comment]
I know, I will improve the code later. I should have told you to look only at the figures for now.

**Comment by cdeil** [comment]
I see. It's here: https://github.com/gammapy/gammapy-benchmarks/blob/10506ccb96194b0e6524e1938618178252fc3145/validation/fermi-3fhl/README.md

**Pull request merged**
